import Head from "next/head";
import GalleryHome from "../components/GalleryHome/Gallery";
import Footer from "../components/shared/Footer";

export default function Home() {
  return (
    <div className="bg-[#f0f8ff]">
      <Head>
        <title>Animated Image Gallery</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <GalleryHome/>
        <Footer/>
      </main>
    </div>
  );
}
